// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jjiinznpsfouakmkaudp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpqaWluem5wc2ZvdWFrbWthdWRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNjMwNTYsImV4cCI6MjA1OTkzOTA1Nn0.qAL-R2VFx27cC8Y-1MYx9NZDhOd7JTK0FRnKayggTw0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);